### ISSUE TITLE
MappedBuffer.h oddness

### ISSUE THREAD

**Issue by TonyWhitley** [TheIronWolfModding/rF2SharedMemoryMapPlugin#10]
auto isDedicatedServer = **true**;   **_// surely that should be initialised false?_**
if (strstr(moduleName, "Dedicated.exe") == nullptr)
  _strcpy_s(mappingName, fileName);  // Regular client use._
else {
  _// Dedicated server use.  Append processId for dedicated server to allow multiple instances._
  char pid[8] = {};
  sprintf(pid, "%d", ::GetCurrentProcessId());

  if (dedicatedServerMapGlobally)
sprintf(mappingName, "Global\\%s%s", fileName, pid);
  else
sprintf(mappingName, "%s%s", fileName, pid);

  isDedicatedServer = **true**;
}

**Comment by TonyWhitley** [comment]
I found this while unit testing...

**Comment by TheIronWolfModding** [comment]
this is great find Tony, thanks.
