### ISSUE TITLE
Weather info is static, wrong or non existant

### ISSUE THREAD

**Issue by AnthonySLWhite** [TheIronWolfModding/rF2SharedMemoryMapPlugin#5]
Is there a way to check the wind speed, temperature, rain in realtime.
The mWind and the mMinPathWetness comes as 0. 
The mRaining amount is fixed as well as the mAmbientTemp, mTrackTemp and mDarkCloud.
The only value updating is the mMaxPathWetness.
Any other solution for this?

**Comment by TheIronWolfModding** [comment]
This is rF2 bug/limitation.  You may want to ask S397 to fix it.

**Comment by TheIronWolfModding** [comment]
If you are using simhub, make sure you are using latest version.
